namespace PowerPilot.Core.Models;

/// <summary>
/// Represents a notification generated by the energy monitoring agent system.
/// </summary>
public class EnergyNotification
{
    /// <summary>
    /// Unique identifier for this notification.
    /// </summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Timestamp when the notification was created.
    /// </summary>
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// The main notification message synthesized from agent contributions.
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// Dictionary mapping agent names to their specific analysis contributions.
    /// Key: agent name (e.g., "energy_analyzer", "appliance_advisor", "timing_optimizer")
    /// Value: the agent's analysis text
    /// </summary>
    public Dictionary<string, string> AgentContributions { get; set; } = new();

    /// <summary>
    /// Notification severity level.
    /// </summary>
    public NotificationSeverity Severity { get; set; } = NotificationSeverity.Info;

    /// <summary>
    /// Whether the notification has been read/acknowledged by the user.
    /// </summary>
    public bool IsRead { get; set; } = false;

    /// <summary>
    /// Current energy surplus in kW that triggered this notification.
    /// </summary>
    public decimal EnergySurplusKw { get; set; }
}

/// <summary>
/// Notification severity levels.
/// </summary>
public enum NotificationSeverity
{
    /// <summary>
    /// Informational notification (default).
    /// </summary>
    Info,

    /// <summary>
    /// Success notification (e.g., optimal energy conditions).
    /// </summary>
    Success,

    /// <summary>
    /// Warning notification (e.g., moderate surplus).
    /// </summary>
    Warning,

    /// <summary>
    /// Important/urgent notification (e.g., high surplus, act soon).
    /// </summary>
    Important
}
